### ISSUE TITLE
czemu

### ISSUE THREAD

**Issue by inzynierr** [noyzys/nautchkafe-vanish#1]
czemu ten plugin siada na butle od vanisha

**Comment by noyzys** [comment]
Uzywales kiedys plynu lub proszku od vanish podczas robienia prania? dla eternalcode to persil lepszy

**Comment by inzynierr** [comment]
no vanish spk w sumie wybiela mi ubrania jak sie upi3rd0le sosem po kebabie

**Comment by inzynierr** [comment]
a persil to taniocha dla wsiokuw, dlatego pewnie eternalcode woli

**Comment by inzynierr** [comment]
oczywiscie no hejt czy cos pozdrawiam z poszanowaniem, Kacper T.

**Comment by noyzys** [comment]
> oczywiscie no hejt czy cos pozdrawiam z poszanowaniem, Kacper T.

Nie uznalem to jako hejt sam sie z tego smialem w sensie to smieszny, idiomatyczny, debilny pomysl z tym vanishem sama idea ale no nudzilo mi sie haha pozdrawiam rowniez
